[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_KEY,REACT_APP_B2_BUCKET_NAME,SUPABASE_URL,REACT_APP_SUPABASE_URL"