[build]
  command = "npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  REACT_APP_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZ2pobGNldGhvZmNvYXhxaHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMDA0ODEsImV4cCI6MjA2Njg3NjQ4MX0.QBMh0hAaKEv6E3clzSdhI7kPOlh6SWwDFG5aq27yUv0"
  REACT_APP_SUPABASE_URL = "https://yegjhlcethofcoaxqhqr.supabase.co"

[context.production.environment]
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_SUPABASE_KEY,REACT_APP_SUPABASE_URL,REACT_APP_B2_BUCKET_NAME"
